name: OTP Kuroko
description: Provide precompiled release OTP asset
inputs:
  secret-token:
    description: A secret token to authenticate on behalf of GitHub Actions
    required: true
  target-pattern:
    description: A tag pattern to match targets. It is used for command `git tag --list [target-pattern]`. Default is `OTP-*`
    required: false
runs:
  using: node12
  main: dist/index.js
